// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckcfgpmzftmklrnhxepj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrY2ZncG16ZnRta2xybmh4ZXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5Njk4OTMsImV4cCI6MjA1NDU0NTg5M30.t7aoz7Qyloy1t8YzphjINHAw0vsa0J1uZCMNMevLepI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);